In [ ]:
import pandas as pd

Task 1 - Load the Dataset

In [2]:
df = pd.read_csv('employee_salary.csv')
print("Dataset Shape:", df.shape)
print("No of rows: ",df.shape[0])
print("No of columns: ",df.shape[1])
print("\nFirst 5 Records:")
display(df.head())
print("\nLast 5 Records:")
display(df.tail())

Dataset Shape: (12, 6)
No of rows:  12
No of columns:  6

First 5 Records:

   EmployeeID     Name Department  Age  Experience   Salary
0         101     John         HR   30         5.0  45000.0
1         102    Smith         IT   28         3.0  55000.0
2         103    Alice    Finance   35        10.0  75000.0
3         104      Bob         IT   40        15.0  90000.0
4         105  Charlie         HR   25         2.0  40000.0

Last 5 Records:

    EmployeeID   Name Department  Age  Experience    Salary
7          108  Frank         IT   45        20.0  110000.0
8          109  Grace    Finance   31         6.0   65000.0
9          110  Heidi      Sales   38        12.0   85000.0
10         101   John         HR   30         5.0   45000.0
11         102  Smith         IT   28         3.0   55000.0

Task 2 - Metadata and Statistics

In [3]:

print("Column Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMetadata:")
df.info()

print("\nDescriptive Statistics:")
display(df.describe())

Column Names:
['EmployeeID', 'Name', 'Department', 'Age', 'Experience', 'Salary']

Data Types:
EmployeeID      int64
Name           object
Department     object
Age             int64
Experience    float64
Salary        float64
dtype: object

Metadata:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  12 non-null     int64
 1   Name        12 non-null     object
 2   Department  12 non-null     object
 3   Age         12 non-null     int64
 4   Experience  11 non-null     float64
 5   Salary      11 non-null     float64
dtypes: float64(2), int64(2), object(2)
memory usage: 708.0+ bytes

Descriptive Statistics:

       EmployeeID        Age  Experience         Salary
count   12.000000  12.000000   11.000000      11.000000
mean   104.833333  32.583333    8.000000   65000.000000
std      3.157483   5.822501    5.674504   22360.679775
min    101.000000  25.000000    2.000000   40000.000000
25%    102.000000  28.750000    4.000000   47500.000000
50%    104.500000  30.500000    6.000000   55000.000000
75%    107.250000  35.750000   11.000000   80000.000000
max    110.000000  45.000000   20.000000  110000.000000

Task 3 - Checking Missing Values and Duplicates

In [12]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

print("\nPercentage of Missing Values (%):")
print((df.isnull().sum() / len(df)) * 100)

print("Column with highest missing entries: ")
print(df.isnull().sum().idxmax())

print("Dataset Size Before Cleaning:", len(df))
print("Number of Duplicates:", df.duplicated().sum())

# Clean the dataset
df_cleaned = df.drop_duplicates()
print("Dataset Size After Cleaning:", len(df_cleaned))

Missing Values in Each Column:
EmployeeID    0
Name          0
Department    0
Age           0
Experience    1
Salary        1
dtype: int64

Percentage of Missing Values (%):
EmployeeID    0.000000
Name          0.000000
Department    0.000000
Age           0.000000
Experience    8.333333
Salary        8.333333
dtype: float64
Column with highest missing entries:
Experience
Dataset Size Before Cleaning: 12
Number of Duplicates: 2
Dataset Size After Cleaning: 10